### ISSUE TITLE
Admin inlines

### ISSUE THREAD

**Issue by vapkarian** [gregmuellegger/django-sortedm2m#20] opened 2014-03-28 15:52 UTC
If inline form contains sortedm2m field, drag-n-drop won't worked when I click "Add another inline form". How I can re-init this functionality? Also, I cannot change ordering of selected items without uncheking one of them, changing ordering and checking again.

**Comment by outime** [comment] 2015-01-08 18:24
I was about to write a patch for the second part of the issue but I can't reproduce it... Am I missing something? Check https://www.youtube.com/watch?v=p3F517T0iyM and prove me wrong :) 

Using Django 1.7.2 with:

```from django.db import models
from sortedm2m.fields import SortedManyToManyField

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)

    def __unicode__(self):
        return unicode(self.choice_text)

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    choices = SortedManyToManyField(Choice)

    def __unicode__(self):
        return unicode(self.question_text)```

**Comment by gregmuellegger** [comment] 2015-01-09 14:23
Cool ok. Thanks for your efforts. So I will close this since we cannot reproduce it.
If someone still finds this broken, feel free to reopen.

**Closed by gregmuellegger** 2015-01-09 14:23 UTC
