### ISSUE TITLE
IntegrityError when migrating model

### ISSUE THREAD

**Issue by rolandgeider** [gregmuellegger/django-sortedm2m#45] opened 2015-02-02 19:58 UTC
Perhaps I am missing something very obvious, but after migrating an existing m2m to a sorted m2m I get an IntegrityError (development setup, so using sqlite)

```
django.db.utils.IntegrityError: NOT NULL constraint failed: manager_set_exercises__new.sort_value
```

Shouldn't ```make_sort_by_field``` in operations.py add a sort field with a default?

```field = models.IntegerField(name=SORT_VALUE_FIELD_NAME, default=1)```

**Comment by gregmuellegger** [comment] 2015-02-05 09:23
You are absolutely right. The tests weren't good in that direction. This should be fixed in current master. I will upload a new version to PyPI once you can confirm that the issue is fixed for you.

**Comment by rolandgeider** [comment] 2015-02-05 17:10
@gregmuellegger I just did a quick test with my migrated app, so far everything looks good

**Comment by gregmuellegger** [comment] 2015-02-06 10:50
Thanks for the feedback, I just released 0.9.2
https://pypi.python.org/pypi/django-sortedm2m/

**Comment by gregmuellegger** [comment] 2015-02-06 11:33
Ohoh, seems that there are still problems with Postgres that needs fixing.
I will try to come up with a fix.

**Comment by rolandgeider** [comment] 2015-02-06 11:43
Oh, I only tested it with sqlite. Just ping me again if you want me to test it on postgres

**Comment by gregmuellegger** [comment] 2015-02-06 14:43
Now there is 0.9.3 with passing tests for postgres and mysql: 
https://pypi.python.org/pypi/django-sortedm2m/

**Closed by gregmuellegger** 2015-02-06 14:43 UTC
